Fair=0;
No_Of_Sent_bits=1000;
%[SNRe,BER_AWGN]=MainSimulator(0,30,0,0,Fair,No_Of_Sent_bits);
%[SNRe,BER_Rayleigh_No_FEC]=MainSimulator(0,30,1,0,Fair,No_Of_Sent_bits);
%[SNRe,BER_Rayleigh_No_Rept3]=MainSimulator(0,14,1,1,Fair,No_Of_Sent_bits);
%[SNRe,BER_Rayleigh_No_Rept5]=MainSimulator(-4,4,1,2,Fair,No_Of_Sent_bits);
[SNRe,BER_Rayleigh_No_Hamming4_7]=MainSimulator(0,20,1,3,Fair,No_Of_Sent_bits);
[SNRe,BER_Rayleigh_No_Hamming11_15]=MainSimulator(0,20,1,4,Fair,No_Of_Sent_bits);
figure(1);
% semilogy(SNRe,BER_AWGN,'b');
% hold on;
% semilogy(SNRe,BER_Rayleigh_No_FEC,'r');
% hold on;
% semilogy(SNRe,BER_Rayleigh_No_Rept3,'y');
% hold on;
% semilogy(SNRe,BER_Rayleigh_No_Rept5,'o');
% hold on;
semilogy(SNRe,BER_Rayleigh_No_Hamming4_7,'r');
 hold on;
semilogy(SNRe,BER_Rayleigh_No_Hamming11_15,'b');
% legend('AWGN','AWGN with Reyleigh','FEC Rept 1/3','Rept 1/5','Hamm 4/7','Hamm 11/15');
